import {
  Archive,
  Bookmark,
  BookmarkPlus,
  BookOpen,
  BrainCircuit,
  Briefcase,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CodeXml,
  Coffee,
  Compass,
  Copy,
  ExternalLink,
  FileText,
  FlaskConical,
  Folder,
  FolderPlus,
  Folders,
  Gamepad2,
  Globe,
  GraduationCap,
  Hash,
  Heart,
  ImagePlus,
  Inbox,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link as LinkIcon,
  List as ListIcon,
  LoaderCircle,
  Map as MapIcon,
  Music,
  Newspaper,
  Palette,
  PencilLine,
  PenTool,
  Plane,
  Play,
  Plus,
  Search,
  SearchX,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tag as TagIcon,
  Terminal,
  Trash2,
  X,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "./names";

export const ICON_COMPONENTS: Readonly<Record<IconName, LucideIcon>> = {
  archive: Archive,
  bookmark: Bookmark,
  "bookmark-plus": BookmarkPlus,
  "book-open": BookOpen,
  "brain-circuit": BrainCircuit,
  briefcase: Briefcase,
  camera: Camera,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "code-xml": CodeXml,
  coffee: Coffee,
  compass: Compass,
  copy: Copy,
  "external-link": ExternalLink,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  folder: Folder,
  "folder-plus": FolderPlus,
  folders: Folders,
  "gamepad-2": Gamepad2,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hash: Hash,
  heart: Heart,
  "image-plus": ImagePlus,
  inbox: Inbox,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  lightbulb: Lightbulb,
  link: LinkIcon,
  list: ListIcon,
  "loader-circle": LoaderCircle,
  map: MapIcon,
  music: Music,
  newspaper: Newspaper,
  palette: Palette,
  "pencil-line": PencilLine,
  "pen-tool": PenTool,
  plane: Plane,
  play: Play,
  plus: Plus,
  search: Search,
  "search-x": SearchX,
  "shopping-bag": ShoppingBag,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  tag: TagIcon,
  terminal: Terminal,
  "trash-2": Trash2,
  x: X,
};

export const CHANNEL_ICON_CHOICES: readonly IconName[] = [
  "book-open",
  "play",
  "flask-conical",
  "terminal",
  "hash",
  "bookmark",
  "lightbulb",
  "star",
  "heart",
  "music",
  "camera",
  "palette",
  "briefcase",
  "graduation-cap",
  "coffee",
  "globe",
  "code-xml",
  "pen-tool",
  "archive",
  "inbox",
  "map",
  "compass",
  "sparkles",
  "newspaper",
  "leaf",
  "gamepad-2",
  "shopping-bag",
  "plane",
];
